### ISSUE TITLE
Problem with GRCh38 annotation (ExAC and Thousand Genomes missing)

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-annotator#22]
```
com.github.bihealth.varfish_annotator.VarfishAnnotatorException: Problem with querying ExAC
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.getDbInfo(AnnotateVcf.java:857)
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.annotateVariantContext(AnnotateVcf.java:384)
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.annotateVcf(AnnotateVcf.java:270)
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.run(AnnotateVcf.java:152)
        at com.github.bihealth.varfish_annotator.VarfishAnnotatorCli.main(VarfishAnnotatorCli.java:57)
Caused by: org.h2.jdbc.JdbcSQLException: Table "EXAC_VAR" not found; SQL statement:
SELECT exac_af, exac_het, exac_hom, exac_hemi FROM exac_var WHERE (release = ?) AND (chrom = ?) AND (start = ?) AND (ref = ?) AND (alt = ?) [42102-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5920)
        at org.h2.command.Parser.readTableFilter(Parser.java:1430)
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)
        at org.h2.command.Parser.parseSelectSimple(Parser.java:2287)
        at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
        at org.h2.command.Parser.parseSelect(Parser.java:1919)
        at org.h2.command.Parser.parsePrepared(Parser.java:463)
        at org.h2.command.Parser.parse(Parser.java:335)
        at org.h2.command.Parser.parse(Parser.java:307)
        at org.h2.command.Parser.prepareCommand(Parser.java:278)
        at org.h2.engine.Session.prepareLocal(Session.java:611)
        at org.h2.engine.Session.prepareCommand(Session.java:549)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
        at com.github.bihealth.varfish_annotator.annotate.AnnotateVcf.getDbInfo(AnnotateVcf.java:839)

```

**Comment by holtgrewe** [comment]
Adding tests in #38 and the problem does not exist any more.
