### ISSUE TITLE
varfish-annotator self-test has wrong assumptions about gnomad_genomes_var

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-annotator#51]
**Describe the bug**
There is no chrY in gnomAD genomes. This leads to an error report (workaround is to only check for chr1)

**To Reproduce**
1. Run annotate step. See problem below.

```
INFO: Genome looks like GRCh37 (sequence only; regardless of 'chr' prefix).
Problem with database self-test: Could not found the following chromosomes for table gnomad_genome_var: [Y]
com.github.bihealth.varfish_annotator.utils.SelfTestFailedException: Could not found the following chromosomes for table gnomad_genome_var: [Y]
        at com.github.bihealth.varfish_annotator.utils.DatabaseSelfTest.selfTestDb(DatabaseSelfTest.java:71)
        at com.github.bihealth.varfish_annotator.utils.DatabaseSelfTest.selfTest(DatabaseSelfTest.java:36)
        at com.github.bihealth.varfish_annotator.annotate_svs.AnnotateSvsVcf.run(AnnotateSvsVcf.java:187)
        at com.github.bihealth.varfish_annotator.VarfishAnnotatorCli.main(VarfishAnnotatorCli.java:69)
```

**Expected behavior**
Annotation should run through

**Screenshots**

**Additional context**
Only GRCh37 is affected.

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
gnomAD genomes does not have chrY

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Do not check chrY for gnomAD genomes.

**Affected Components**
VarFish Annotator

**Affected Modules/Files**
N/A

**Required Architectural Changes**
None

**Required Database Changes**
No

**Backport Possible?**
No

**Resolution Sketch**
Skip check.
