### ISSUE TITLE
NPE when annotating Delly2 files

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-annotator#88]
```
Exception in thread "main" java.lang.NullPointerException
        at com.github.bihealth.varfish_annotator.annotate_svs.AnnotateSvsVcf.mergeChromRecords(AnnotateSvsVcf.java:348)
        at com.github.bihealth.varfish_annotator.annotate_svs.AnnotateSvsVcf.mergeSortedGts(AnnotateSvsVcf.java:278)
        at com.github.bihealth.varfish_annotator.annotate_svs.AnnotateSvsVcf.run(AnnotateSvsVcf.java:210)
        at com.github.bihealth.varfish_annotator.VarfishAnnotatorCli.main(VarfishAnnotatorCli.java:72)
```

**Comment by holtgrewe** [comment]
**Root Cause Analysis**
Delly2 writes out the `INFO/SVMETHOD` tag whose value is `ENSEMBL.DELLY` while we use `DELLY2_SV` internally to differentiate from Delly2 CNV.
